[workspace]

members = [
    "casper-private-auction-core",
    "english-auction-installer",
    "dutch-auction-installer",
    "swap-installer",
    "bid-purse",
    "tests"
]

[profile.release]
lto = true
opt-level = "z"